#!/usr/bin/env bash
set -euo pipefail

CHMARL_REPO="${1:-../EcoFairCHAMRL}"
EPISODES="${2:-2000}"
OUT_ROOT="${3:-results/chmarl_ablation}"
PYTHON_BIN="${PYTHON_BIN:-python}"

if [[ ! -d "$CHMARL_REPO" ]]; then
  echo "CHMARL repository not found: $CHMARL_REPO" >&2
  exit 1
fi

CHMARL_SCRIPT="$CHMARL_REPO/EcoFairCHMARL.py"
if [[ ! -f "$CHMARL_SCRIPT" ]]; then
  echo "EcoFairCHMARL.py not found at: $CHMARL_SCRIPT" >&2
  exit 1
fi

mkdir -p "$OUT_ROOT"

run_case() {
  local name="$1"
  shift
  local outdir="$OUT_ROOT/$name"
  mkdir -p "$outdir"
  echo "[CHMARL] Running $name -> $outdir"
  "$PYTHON_BIN" "$CHMARL_SCRIPT" --episodes "$EPISODES" --outdir "$outdir" "$@"
}

run_case baseline
run_case emission_cap --emission_cap
run_case fairness --fairness
run_case emission_fairness --emission_cap --fairness
run_case soto --algo SOTO
run_case fen --algo FEN

cat > "$OUT_ROOT/README.md" <<EOF
# CHMARL ablation run

Generated by scripts/chmarl/run_ablation_matrix.sh

- CHMARL repository: $CHMARL_REPO
- Episodes: $EPISODES
- Output root: $OUT_ROOT

Cases:

- baseline
- emission_cap
- fairness
- emission_fairness
- soto
- fen
EOF

echo "[CHMARL] Ablation matrix complete: $OUT_ROOT"
